#!/bin/bash

#Zabbix5.0 Ubuntu 20 mysql  apache

sudo wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1+focal_all.deb
sudo dpkg -i zabbix-release_5.0-1+focal_all.deb
sudo apt update

sudo apt install zabbix-server-mysql  -y
sudo apt install zabbix-frontend-php -y
sudo apt install php7.4-mysql zabbix-apache-conf zabbix-agent -y
sudo apt install git curl php-curl mc htop -y

sudo mysql -uroot -e "create database zabbix character set utf8 collate utf8_bin;"
sudo mysql -uroot -e "grant all privileges on zabbix.* to zabbix@localhost identified by 'passwordfornubies';"
sudo mysql -uroot -e "FLUSH PRIVILEGES;"
sudo mysql -uroot -e "quit"

sudo zcat /usr/share/doc/zabbix-server-mysql/create.sql.gz | sudo mysql -uzabbix zabbix -ppasswordfornubies

sudo cp ~/zabconf/zabbix_server.conf /etc/zabbix
sudo cp ~/zabconf/apache.conf /etc/zabbix

sudo service apache2 restart
sudo service zabbix-server start
sudo update-rc.d zabbix-server enable
